server:
  port: 8002
#  数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aigou_product
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: PRODUCT-SERVER
mybatis-plus:
  type-aliases-package: cn.ken.egou.domain
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka-7001.com:7001/eureka

