server:
  port: 8002
#  数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aigou_product
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: PRODUCT-SERVER
  devtools:
    remote:
      restart:
        enabled: true #是否开启开发者工具（true/false） #additional-paths: src/main/java exclude: static/**,WEB-INF/view/**
    restart:
      additional-paths: src/main/java
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300 #java的客户端要用9300 服务器地址
mybatis-plus:
  type-aliases-package: cn.ken.egou.domain
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka-7001.com:7001/eureka

logging:
  level:
    cn.ken.egou: debug